/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package internal_pilihan;


import Koneksi.simpanpenjualanrumah;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.StringTokenizer;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class penjualan_rumah extends javax.swing.JInternalFrame {
    
    public StringTokenizer token;
public String gantiformat="";
    public double harga_tanah;
    public double harga_bangunan;
    public int luas_tanah;
    public int tanah_tersedia;
    public int harga;
    public long dp;
    public int lama_cicilan;
    public int ppn;
    public int cicilan_perbulan;
    public String area;
    public String Pesan;
    
    public penjualan_rumah() {
        initComponents();
        namaButton();
    }
        String namaButton() {
            if (tipe_36.isSelected()) {
                return tipe_36.getText();
            } else if (tipe_45.isSelected()) {
                return tipe_45.getText();
            } else if (tipe_54.isSelected()) {
                return tipe_54.getText();
            }
        return null;
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnamapemesan = new javax.swing.JTextField();
        txthargatanah = new javax.swing.JTextField();
        txtarea = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        tipe_36 = new javax.swing.JRadioButton();
        tipe_54 = new javax.swing.JRadioButton();
        tipe_45 = new javax.swing.JRadioButton();
        txthargabangunan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtluastanahasli = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtluastanahtersedia = new javax.swing.JTextField();
        txtdp = new javax.swing.JTextField();
        txtlamacicilan = new javax.swing.JTextField();
        txtppn = new javax.swing.JTextField();
        txtcicilanperbulan = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtsetuju = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Jgambar = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Nama Pemesan");

        jLabel2.setText("Harga Tanah/m2");

        jLabel3.setText("Area");

        txtarea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bougenvile", "Melati", "Flamboyan", "Kemahalan" }));
        txtarea.setSelectedIndex(-1);
        txtarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtareaActionPerformed(evt);
            }
        });

        jLabel4.setText("Harga Bangunan");

        jLabel5.setText("Tipe Rumah");

        jLabel6.setText("Luas Tanah Asli");

        buttonGroup1.add(tipe_36);
        tipe_36.setText("Tipe-36");
        tipe_36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipe_36ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tipe_54);
        tipe_54.setText("Tipe-54");
        tipe_54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipe_54ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tipe_45);
        tipe_45.setText("Tipe-45");
        tipe_45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipe_45ActionPerformed(evt);
            }
        });

        jLabel7.setText("Luas Tanah Tersedia");

        jLabel8.setText("Harga");

        jLabel9.setText("DP");

        jLabel10.setText("Lama Cicilan");

        jLabel11.setText("PPN(10%)");

        jLabel12.setText("Cicilan/bln");

        jButton1.setText("PROSES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("SIMPAN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtsetuju.setText("Setuju");
        txtsetuju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsetujuActionPerformed(evt);
            }
        });

        jLabel13.setText("Bulan");

        jLabel14.setText("Penjualan Rumah");

        Jgambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton4.setText("Lihat Data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtarea, 0, 120, Short.MAX_VALUE)
                                    .addComponent(txthargatanah)
                                    .addComponent(txtnamapemesan)))
                            .addComponent(Jgambar, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(213, 213, 213)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel8))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(tipe_36)
                                    .addComponent(tipe_45)
                                    .addComponent(jLabel4)
                                    .addComponent(tipe_54))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcicilanperbulan)
                            .addComponent(txtppn)
                            .addComponent(txtlamacicilan)
                            .addComponent(txtharga)
                            .addComponent(txtdp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtluastanahtersedia, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtluastanahasli, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txthargabangunan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsetuju)
                    .addComponent(jLabel13))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tipe_36)
                                .addGap(18, 18, 18)
                                .addComponent(tipe_45)
                                .addGap(18, 18, 18)
                                .addComponent(tipe_54)
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtlamacicilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtppn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtcicilanperbulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtsetuju))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2)
                                    .addComponent(jButton3)
                                    .addComponent(jButton4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtnamapemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txthargabangunan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txthargatanah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtluastanahasli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtluastanahtersedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jgambar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtareaActionPerformed

area=(String)txtarea.getSelectedItem();
if("Bougenvile".equals(area)){
harga_tanah=500000;
txthargatanah.setText("500.000");
harga_bangunan=90000000;
txthargabangunan.setText("90.000.000");
ImageIcon gambar = new ImageIcon("src/Kumpulan_Gambar/Bougenvile.jpg");
Jgambar.setIcon(gambar);
}else if("Melati".equals(area))
{
harga_tanah=600000;
txthargatanah.setText("600.000");
harga_bangunan=120000000;
txthargabangunan.setText("120.000.000");
ImageIcon gambar = new ImageIcon("src/Kumpulan_Gambar/Melati.jpg");
Jgambar.setIcon(gambar);
}else if("Flamboyan".equals(area))
{
harga_tanah=700000;
txthargatanah.setText("700.000");
harga_bangunan=150000000;
txthargabangunan.setText("150.000.000");
ImageIcon gambar = new ImageIcon("src/Kumpulan_Gambar/Flamboyan.jpg");
Jgambar.setIcon(gambar);
}else 
{
harga_tanah=0;
txthargatanah.setText("-");
harga_bangunan=0;
txthargabangunan.setText("-");
ImageIcon gambar = new ImageIcon("src/Kumpulan_Gambar/Kemahalan.jpg");
Jgambar.setIcon(gambar);
}// TODO add your handling code here:
    }//GEN-LAST:event_txtareaActionPerformed

    private void tipe_36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipe_36ActionPerformed
txtluastanahasli.setText("90");
harga_bangunan=90;       // TODO add your handling code here:
    }//GEN-LAST:event_tipe_36ActionPerformed

    private void tipe_45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipe_45ActionPerformed
txtluastanahasli.setText("120");
harga_bangunan=120;       // TODO add your handling code here:
    }//GEN-LAST:event_tipe_45ActionPerformed

    private void tipe_54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipe_54ActionPerformed
txtluastanahasli.setText("140");
harga_bangunan=140;        // TODO add your handling code here:
    }//GEN-LAST:event_tipe_54ActionPerformed

    private void txtsetujuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsetujuActionPerformed
if(txtsetuju.isSelected()==true){
 Pesan = "Klik Ok Untuk Menyetujui";
JOptionPane.showMessageDialog(null,Pesan,"Terimakasih",
JOptionPane.INFORMATION_MESSAGE);
}else{
 Pesan = "Yaki  n Nih Gak Setuju Beli?";
JOptionPane.showMessageDialog(null,Pesan,"Kenapa Gak Jadi Setuju?",
JOptionPane.QUESTION_MESSAGE);
        
}        // TODO add your handling code here:
    }//GEN-LAST:event_txtsetujuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//harga_tanah=Integer.parseInt(txthargatanah.getText());
//harga_bangunan=Integer.parseInt(txthargabangunan.getText());
luas_tanah=Integer.parseInt(txtluastanahasli.getText());
//tanah_tersedia=Integer.parseInt(txtluastanahtersedia.getText());
dp=(long) Double.parseDouble(txtdp.getText());
//dp=Integer.parseInt(txtdp.getText());
//dp=(string) Float.parseFloat(txtdp.getText());
//dp=Integer.valueOf (txtdp.getText()).intValue();
//dp = getStrToInt(txtdp.getText());

lama_cicilan=Integer.parseInt(txtlamacicilan.getText());
harga= (int) ((harga_tanah*luas_tanah)+harga_bangunan) ; 
gantiformat=NumberFormat.getNumberInstance(Locale.ENGLISH).format(harga
);
token=new StringTokenizer(gantiformat,".");
gantiformat=token.nextToken();
gantiformat=gantiformat.replace(',', '.');
txtharga.setText(gantiformat);


ppn = (harga * 10) / 100;
txtppn.setText(""+ppn);

gantiformat=NumberFormat.getNumberInstance(Locale.ENGLISH).format(ppn
);
token=new StringTokenizer(gantiformat,".");
gantiformat=token.nextToken();
gantiformat=gantiformat.replace(',', '.');
txtppn.setText(gantiformat);


cicilan_perbulan= (int)(harga+ppn-dp)/lama_cicilan;
txtcicilanperbulan.setText(""+cicilan_perbulan);

gantiformat=NumberFormat.getNumberInstance(Locale.ENGLISH).format(dp
);
token=new StringTokenizer(gantiformat,".");
gantiformat=token.nextToken();
gantiformat=gantiformat.replace(',', '.');
txtdp.setText(gantiformat);

gantiformat=NumberFormat.getNumberInstance(Locale.ENGLISH).format(cicilan_perbulan
);
token=new StringTokenizer(gantiformat,".");
gantiformat=token.nextToken();
gantiformat=gantiformat.replace(',', '.');
txtcicilanperbulan.setText(gantiformat);




    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   simpanpenjualanrumah penjualan_rumah= new simpanpenjualanrumah();
   penjualan_rumah.nama_pemesan=txtnamapemesan.getText();
   penjualan_rumah.area=(String) txtarea.getSelectedItem();
   penjualan_rumah.tipe_rumah=namaButton();
   penjualan_rumah.luas_tanah=txtluastanahasli.getText();
   penjualan_rumah.harga=txtharga.getText();
   penjualan_rumah.lama_cicilan=txtlamacicilan.getText();
   penjualan_rumah.cicilan_per_bulan=txtcicilanperbulan.getText();

   
   
   
   try{
       penjualan_rumah.simpanpenjualanrumah();
       JOptionPane.showMessageDialog(null,"Berhasil");

   }catch (Exception e){
        JOptionPane.showMessageDialog(null,e);
   }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtnamapemesan.setText("");
        txtarea.setSelectedIndex(-1);
        txtluastanahasli.setText("");
        txtluastanahtersedia.setText("");
        buttonGroup1.clearSelection();
        txthargabangunan.setText("");
        txthargatanah.setText("");
        txtharga.setText("");
        txtdp.setText("");
        txtlamacicilan.setText("");
        txtppn.setText("");
        txtcicilanperbulan.setText("");
        txtsetuju.setSelected(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
tampil_data tampildata = new tampil_data();
this.getParent().add(tampildata);
Dimension gs=tampildata.getSize();
Dimension cs=this.getSize(); 
tampildata.setLocation((gs.width-cs.width)/2,(gs.height-cs.height)/2);
tampildata.setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jgambar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton tipe_36;
    private javax.swing.JRadioButton tipe_45;
    private javax.swing.JRadioButton tipe_54;
    private javax.swing.JComboBox<String> txtarea;
    private javax.swing.JTextField txtcicilanperbulan;
    private javax.swing.JTextField txtdp;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txthargabangunan;
    private javax.swing.JTextField txthargatanah;
    private javax.swing.JTextField txtlamacicilan;
    private javax.swing.JTextField txtluastanahasli;
    private javax.swing.JTextField txtluastanahtersedia;
    private javax.swing.JTextField txtnamapemesan;
    private javax.swing.JTextField txtppn;
    private javax.swing.JCheckBox txtsetuju;
    // End of variables declaration//GEN-END:variables
}
