/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package internal_pilihan;


import javax.swing.table.DefaultTableModel;
import Koneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author ASUS
 */
public class tampil_data extends javax.swing.JInternalFrame {

    /**
     * Creates new form tampil_data
     */
    //Connection con;
    //Statement stmt;
    //ResultSet rs;
  
    ResultSet r=null;
    public tampil_data() {
        initComponents();
        
    }
    
    
private void tampildata(){
       DefaultTableModel tbl=new DefaultTableModel();
    tbl.addColumn("Area");
    tbl.addColumn("Tipe Rumah");
    tbl.addColumn("Luas Tanah");
    tbl.addColumn("Harga");
    tbl.addColumn("Lama Cicilan");
    tbl.addColumn("Cicilan/Bln");
 
try{
Connection konek = koneksi.getKoneksi();
String sql="SELECT * FROM tbl_tampildata";
Statement s = konek.createStatement();
ResultSet r = s.executeQuery(sql);
while(r.next()){
        tbl.addRow(new Object[]{ 
            r.getString(2),
            r.getString(3),            
            r.getString(4),
            r.getString(5),
            r.getString(6),
            r.getString(7)});
}
table.setModel(tbl);
}catch(SQLException e){}

}
private void caridata(String key){
    
        try{
            DefaultTableModel tbl=new DefaultTableModel();
            tbl.addColumn("Area");
            tbl.addColumn("Tipe Rumah");
            tbl.addColumn("Luas Tanah");
            tbl.addColumn("Harga");
            tbl.addColumn("Lama Cicilan");
            tbl.addColumn("Cicilan/Bln");
            table.setModel(tbl);
            
            Connection konek = koneksi.getKoneksi();
            //Statement stt=conn.createStatement();
            Statement s = konek.createStatement();
            //tabModel.getDataVector().removeAllElements();
            tbl.getDataVector().removeAllElements();
            //OR luas_tanah LIKE '%"+key+"%' OR harga LIKE '%"+key+"%'
            r=s.executeQuery("SELECT * FROM tbl_tampildata WHERE nama_pemesan LIKE '%"+key+"%'OR area LIKE '%"+key+"%'");  
            while(r.next()){
                Object[] data={
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6),
                    r.getString(7),                            
                };
               tbl.addRow(data);
            }                
        } catch (SQLException ex) {
        System.err.println(ex.getMessage());
        }
}
private void caridataarea(String keyy ){
    
        try{
            DefaultTableModel tbl=new DefaultTableModel();
            tbl.addColumn("Area");
            tbl.addColumn("Tipe Rumah");
            tbl.addColumn("Luas Tanah");
            tbl.addColumn("Harga");
            tbl.addColumn("Lama Cicilan");
            tbl.addColumn("Cicilan/Bln");
            table.setModel(tbl);
            
            Connection konek = koneksi.getKoneksi();
            //Statement stt=conn.createStatement();
            Statement s = konek.createStatement();
            //tabModel.getDataVector().removeAllElements();
            tbl.getDataVector().removeAllElements();
            //OR luas_tanah LIKE '%"+key+"%' OR harga LIKE '%"+key+"%'
            r=s.executeQuery("SELECT * FROM tbl_tampildata WHERE area LIKE '%"+keyy+"%'");  
            while(r.next()){
                Object[] data={
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6),
                    r.getString(7),
                    
                             
                };
               tbl.addRow(data);
            }                
        } catch (SQLException ex) {
        System.err.println(ex.getMessage());
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnamapemesan = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtnamaarea = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TFjumlah = new javax.swing.JTextField();
        TFtotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Cari Data");

        jLabel2.setText("Nama Pemesan");

        jLabel3.setText("Nama Area");

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Area", "Tipe Rumah", "Luas Tanah", "Harga", "Lama Cicilan", "Cicilan/bln"
            }
        ));
        jScrollPane1.setViewportView(table);

        jButton2.setText("Tampikan Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Jumlah Rumah Terjual");

        jLabel5.setText("Total Luas Tanah Terjual");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel5))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFjumlah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)
                            .addComponent(jButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtnamapemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(jButton1))
                                    .addComponent(txtnamaarea, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnamapemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnamaarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
             DefaultTableModel tbl=new DefaultTableModel();
            tbl.addColumn("Area");
            tbl.addColumn("Tipe Rumah");
            tbl.addColumn("Luas Tanah");
            tbl.addColumn("Harga");
            tbl.addColumn("Lama Cicilan");
            tbl.addColumn("Cicilan/Bln");
            table.setModel(tbl);
            
            Connection konek = koneksi.getKoneksi();
               String sql="SELECT * FROM tbl_tampildata";
               Statement s = konek.createStatement();
               ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                tbl.addRow(new String[]{
                    r.getString(1), 
                    r.getString(2), 
                    r.getString(3), 
                    r.getString(4), 
                    r.getString(5), 
                    r.getString(6), 
                    r.getString(7)});
            }
            TFjumlah.setText(Integer.toString(tbl.getRowCount()));
            int total = 0;
            for (int j = 0; j < tbl.getRowCount(); j++) {
                String string = tbl.getValueAt(j, 3).toString();
                int integer = Integer.parseInt(string);
                total += integer;
            }
            TFtotal.setText(Integer.toString(total));
        } catch (NumberFormatException | SQLException ex) {
            System.out.println("Error : " + ex.getMessage());
        }
tampildata();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String key=txtnamapemesan.getText();
        String keyy=txtnamaarea.getText();
        System.out.println(key);
        System.out.println(keyy);

        if(!"".equals(key)){
            caridata(key);
            String pesan = "Data Berhasil Ditemukan";
            JOptionPane.showMessageDialog(null,pesan,"Message",JOptionPane.INFORMATION_MESSAGE);
            
          
           
        }else if(!"".equals(keyy))
        {
            caridataarea(keyy); 
            String pesan = "Data Berhasil Ditemukan";
            JOptionPane.showMessageDialog(null,pesan,"Message",JOptionPane.INFORMATION_MESSAGE);
        
            
        }else
        {
            tampildata();
            String pesan = "Data Tidak Ada Silahkan Cari Lagi";
            JOptionPane.showMessageDialog(null,pesan,"Message",JOptionPane.INFORMATION_MESSAGE);
        }

               // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFjumlah;
    private javax.swing.JTextField TFtotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtnamaarea;
    private javax.swing.JTextField txtnamapemesan;
    // End of variables declaration//GEN-END:variables
}
