/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Folder_Utama;
import internal_pilihan.penjualan_rumah;
import internal_file.Login;
import internal_file.Register;
import internal_pilihan.tampil_data;
import java.awt.Dimension;

/**
 *
 * @author ASUS
 */
public class Main extends javax.swing.JFrame {
    

    /**
     * Creates new form NewJFrame
     */
    public Main() {
        initComponents();
//        menupenjualanrumah.setEnabled(false);
//        menutampilkandata.setEnabled(false);

        //menupilihan.setEnabled(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Dp1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menufile = new javax.swing.JMenu();
        menulogin = new javax.swing.JMenuItem();
        menuregister = new javax.swing.JMenuItem();
        menuexit = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menupilihan = new javax.swing.JMenu();
        menupenjualanrumah = new javax.swing.JMenuItem();
        menutampilkandata = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar4.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar4.add(jMenu7);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout Dp1Layout = new javax.swing.GroupLayout(Dp1);
        Dp1.setLayout(Dp1Layout);
        Dp1Layout.setHorizontalGroup(
            Dp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );
        Dp1Layout.setVerticalGroup(
            Dp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );

        menufile.setText("File");
        menufile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                menufileKeyTyped(evt);
            }
        });

        menulogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menulogin.setText("Login");
        menulogin.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
                menuloginMenuKeyTyped(evt);
            }
        });
        menulogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuloginActionPerformed(evt);
            }
        });
        menufile.add(menulogin);

        menuregister.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuregister.setText("Register");
        menuregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuregisterActionPerformed(evt);
            }
        });
        menufile.add(menuregister);

        menuexit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuexit.setText("Log Out");
        menufile.add(menuexit);

        jMenuItem6.setText("Exit");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menufile.add(jMenuItem6);

        jMenuBar1.add(menufile);

        menupilihan.setText("Pilihan");
        menupilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupilihanActionPerformed(evt);
            }
        });

        menupenjualanrumah.setText("Penjualan_rumah");
        menupenjualanrumah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupenjualanrumahActionPerformed(evt);
            }
        });
        menupilihan.add(menupenjualanrumah);

        menutampilkandata.setText("Tampilkan Data");
        menutampilkandata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutampilkandataActionPerformed(evt);
            }
        });
        menupilihan.add(menutampilkandata);

        jMenuBar1.add(menupilihan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dp1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dp1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void menuloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuloginActionPerformed
Login Log= new Login();
Dp1.add(Log);

//membuat tengah Jinternal
//mencari ukuran panel
Dimension gs=Dp1.getSize();
//mencari ukuran Jinternal
Dimension cs=Log.getSize();
//hitung
Log.setLocation((gs.width-cs.width)/2,(gs.height-cs.height)/2);
//tampilkan
Log.setVisible(true);


// TODO add your handling code here:
    }//GEN-LAST:event_menuloginActionPerformed

    private void menuregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuregisterActionPerformed
Register dua= new Register();
Dp1.add(dua);
dua.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_menuregisterActionPerformed

    private void menupilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupilihanActionPerformed
//menupenjualanrumah.setEnabled(true);
//menutampilkandata.setEnabled(true);
//menupenjualanrumah.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_menupilihanActionPerformed

    private void menupenjualanrumahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupenjualanrumahActionPerformed
penjualan_rumah jualrumah= new penjualan_rumah();
Dp1.add(jualrumah);
jualrumah.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_menupenjualanrumahActionPerformed

    private void menuloginMenuKeyTyped(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_menuloginMenuKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_menuloginMenuKeyTyped

    private void menufileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menufileKeyTyped
       // TODO add your handling code here:
    }//GEN-LAST:event_menufileKeyTyped

    private void menutampilkandataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutampilkandataActionPerformed
tampil_data tampildata= new tampil_data();
Dp1.add(tampildata);
tampildata.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_menutampilkandataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Dp1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem menuexit;
    private javax.swing.JMenu menufile;
    private javax.swing.JMenuItem menulogin;
    private javax.swing.JMenuItem menupenjualanrumah;
    private javax.swing.JMenu menupilihan;
    private javax.swing.JMenuItem menuregister;
    private javax.swing.JMenuItem menutampilkandata;
    // End of variables declaration//GEN-END:variables
}
